name: CI

on:
  schedule:
    - cron: 0 10 * * 5

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: Initialize
      run: |
        # 对于deb系 (debian/ubuntu)：
        sudo apt update
        sudo apt install unzip libtool-bin curl cmake gperf gawk flex bison nano xxd \
        cpio git python-docutils gettext automake autopoint texinfo build-essential help2man \
        pkg-config zlib1g-dev libgmp3-dev libmpc-dev libmpfr-dev libncurses5-dev libltdl-dev
        git clone --depth=1 https://github.com/westernpan/rt-n56u.git /opt/rt-n56u
    - name: Compile
      run: |
        cd /opt/rt-n56u/toolchain-mipsel
        ./clean_toolchain
        ./build_toolchain
        #mkdir -p toolchain-3.4.x
        #wget https://github.com/hanwckf/padavan-toolchain/releases/download/v1.0/mipsel-linux-uclibc.tar.xz
        #tar -xvf mipsel-linux-uclibc.tar.xz -C toolchain-3.4.x
    - name: Compress
      run: |
        tar cvf toolchain-3.4.x.tar toolchain-3.4.x/
        xz -z toolchain-3.4.x.tar
    - name: Upload toolchain
      uses: actions/upload-artifact@master
      with:
          name: toolchain
          path: /opt/rt-n56u/toolchain-mipsel/toolchain-3.4.x.tar.xz
    - name: Build firmware
      run: |
        cd /opt/rt-n56u/trunk
        sudo ./clear_tree
        sudo ./build_firmware_modify DIR-878
        #sudo cp -f /opt/rt-n56u/trunk/images/*.trx /mnt/c
    - name: upload artifact
      uses: actions/upload-artifact@master
      with:
        name: dir878 firmware
        path: /opt/rt-n56u/trunk/images/
