name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: 
        sudo sed -i 's#http://archive.ubuntu.com#https://mirrors.huaweicloud.com#' /etc/apt/sources.list
        sudo sed -i 's#http://security.ubuntu.com#https://mirrors.huaweicloud.com#' /etc/apt/sources.list
        sudo apt update
        sudo apt upgrade
        sudo chmod 777 /opt
    - name: Run a multi-line script
      run: |
        # 对于deb系 (debian/ubuntu)：
        sudo apt install unzip libtool-bin curl cmake gperf gawk flex bison nano xxd \
        cpio git python-docutils gettext automake autopoint texinfo build-essential help2man \
        pkg-config zlib1g-dev libgmp3-dev libmpc-dev libmpfr-dev libncurses5-dev libltdl-dev
        git clone --depth=1 https://github.com/westernpan/rt-n56u.git /opt/rt-n56u
        cd /opt/rt-n56u/trunk
        ./clean_toolchain
        ./build_toolchain
        sudo ./clear_tree
        sudo ./build_firmware_modify DIR-878
